[package]
edition = "2021"
name    = "loru-schemas"
version = "0.3.3"

  [package.metadata.loru]
  lockfile = "../.loru/Cargo.lock"

[dependencies]
serde      = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
name = "loru_schemas"
path = "src/lib.rs"
