[package]
edition = "2021"
name = "loru-schemas"
version = "0.3.4"
metadata = "[object Object]"
[dependencies]
serde = "[object Object]"
serde_json = "1.0"
[lib]
name = "loru_schemas"
path = "src/lib.rs"
